### ISSUE TITLE
Workflow Error

### ISSUE THREAD

**Issue by AtomicGamer9523** [Gl1tchblade/Gl1tchblade.github.io#1]
**Your workflow doesn't push the latest commits to prod because it doesn't sufficient permissions!**
This is your workflow:
```yaml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
```
Just add these 3 lines before the `on` section:
```diff
+ permissions: # sets the permissions for the workflow
+   contents: write # Allows to write content (data)
+   pages: write # Allows to deploy to github servers
```
